export const ADD_ARTICLE = "ADD_ARTICLE";
export const GET_COMPANY = "GET_COMPANY";
export const CREATE_COMPANY = "CREATE_COMPANY";
export const DASHBOARD_TOGGLE = "DASHBOARD_TOGGLE";
export const FORM_TOGGLE = "FORM_TOGGLE";
export const CREATE_SHAREHOLDER = "CREATE_SHAREHOLDER";